#!/usr/bin/python3

import os
import shlex
import sys
from typing import List

args = sys.argv[1:]

opts_list = []
is_opt = False
to_pop: List[int] = []
for n, arg in enumerate(args):
    if arg == "-o":
        opts_list.append(arg)
        is_opt = True
        to_pop.append(n)
    elif is_opt:
        opts_list.append(arg)
        is_opt = False
        to_pop.append(n)
    else:
        break

for x in reversed(to_pop):
    args.pop(x)


cmd = ["ssh"] + opts_list + [args[1], " ".join(shlex.quote(x) for x in args[2:])]
cmd = [
    "qvm-run",
    "-a",
    "--nogui",
    "--pass-io",
    args[0],
    " ".join(shlex.quote(x) for x in cmd),
]
os.execvp("qvm-run", cmd)
